branches:
  only:
    - master

image:
- Visual Studio 2019

services:
  - mssql2017

install:
  - ps: choco install make
  
# before_build:
#   - cmd: make --version
#   - cmd: make database DBSERVER="(local)\SQL2017" DBUSER=migration-runner DBPASSWORD="Passw0rd12!"

build_script:
  - cmd: make build

# after_build:
#   - ps: | 
#         [Environment]::SetEnvironmentVariable("identityConnection", "Server=(local)\SQL2017;Database=identity;User ID=migration-runner;Password=Passw0rd12!", "Machine")
#   - ps: RefreshEnv
#   - cmd: make test
#   - cmd: make cleanup-db DBSERVER="(local)\SQL2017" DBUSER=migration-runner
#   - cmd: make package CONFIGURATION=Release BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%
  
# artifacts:
#   - path: '**\*.nupkg' # push all *.nupkg files in build directory recursively