version: "3.4"

services:
  nginx: 
    image: nginx:latest
    container_name: nginx-rproxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ~/.aspnet/https/:/etc/ssl
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - identity-server
  
  # client-webapp:
  #   image: hemantksingh/client-webapp:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client-webapp
  #   container_name: client-webapp
  #   volumes:
  #     - ~/.aspnet/https/:/https/
  #   ports:
  #     - 5001:80
  #     - 8001:443
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=https://+;http://+:5001
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=password
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/service-identity.pfx
  #   depends_on: 
  #     - identity-server
  
  identity-server:
    image: hemantksingh/identity-server:latest
    build:
      context: .
      dockerfile: Dockerfile.identity-server
    container_name: identity-server
    volumes:
      - ~/.aspnet/https/:/https:ro
    expose:
      - "5000"
      - "443"
    # ports:
    #   - 80:5000
    #   - 443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # The base dotnet/core/aspnet image sets ASPNETCORE_URLS to http://+:80 which means by default the app starts on port 80
      - ASPNETCORE_URLS=https://+;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/service-identity.pfx
  