version: "3.3"

services:
  nginx: 
    image: nginx:latest
    container_name: nginx-rproxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  
  identity-server:
    image: hemantksingh/identity-server:latest
    container_name: identity-server
    expose:
      - "5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development